# Generated by Django 6.0.7 on 2026-07-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('marque_ges', models.CharField(blank=True, max_length=50, null=True)),
                ('puissance_kva', models.CharField(blank=True, max_length=50, null=True)),
                ('capacite_cuve_principale', models.IntegerField(default=0)),
                ('capacite_cuve_journaliere', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReleveSemainier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_code', models.CharField(max_length=20)),
                ('quantite_cuve_p', models.IntegerField(default=0)),
                ('quantite_cuve_j', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('F', 'Fonctionnel'), ('P', 'En Panne'), ('HS', 'Hors Service')], default='F', max_length=2)),
                ('compteur_horaire', models.FloatField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releve_set', to='core.site')),
            ],
            options={
                'unique_together': {('site', 'semaine_code')},
            },
        ),
    ]
