# Generated by Django 6.0.7 on 2026-07-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fiche', models.DateField()),
                ('semaine', models.CharField(help_text='Ex: 13 au 17 Juillet 2026', max_length=50)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('date_importation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='code_site',
            field=models.CharField(default='SITE_TEMP', help_text='Ex: BEPANDA_INT', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='capacite_cuve_journaliere',
            field=models.FloatField(default=0.0, help_text='En Litres'),
        ),
        migrations.AlterField(
            model_name='site',
            name='capacite_cuve_principale',
            field=models.FloatField(default=0.0, help_text='En Litres'),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='puissance_kva',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Depotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depotage', models.DateField()),
                ('type_mouvement', models.CharField(choices=[('EXTERNE', 'Livraison Fournisseur / Marketeur'), ('INTERNE', 'Transfert inter-sites')], default='EXTERNE', max_length=10)),
                ('volume_litres', models.FloatField(help_text='Quantité en Litres')),
                ('reference_ou_fournisseur', models.CharField(help_text='Ex: Bon de livraison Neptune Oil ou camion', max_length=100)),
                ('site_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotages_entrants', to='core.site')),
                ('site_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotages_sortants', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='LigneRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_ges', models.CharField(choices=[('F', 'Fonctionnel'), ('P', 'Panne / Partiel'), ('HS', 'Hors Service')], default='F', max_length=2)),
                ('volume_cuve_principale', models.FloatField(default=0.0)),
                ('volume_cuve_journaliere', models.FloatField(default=0.0)),
                ('compteur_horaire', models.FloatField(default=0.0, help_text='Heures de fonctionnement')),
                ('observations', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='core.site')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.rapporthebdomadaire')),
            ],
        ),
        migrations.DeleteModel(
            name='ReleveSemainier',
        ),
    ]
