export const historicalData = [
  { semaine: "22-26 Juin", stockTotal: 34500, consommation: 1200, pompesHS: 2 },
  { semaine: "06-10 Juillet", stockTotal: 32200, consommation: 2300, pompesHS: 3 },
  { semaine: "13-17 Juillet", stockTotal: 58866, consommation: 1950, pompesHS: 3 }, // Après livraison Neptune Oil
];

export const sitesData = [
  {
    id: 1,
    site: "BEPANDA INTERNATIONAL",
    marque: "SDMO",
    puissance: "20000X2",
    etat: "F",
    cuvePrincipale: 10000,
    quantiteCuveP: 22462,
    cuveJournaliere: 1000,
    quantiteCuveJ: 1000,
    compteurHoraire: 1877,
    observation: "Ravitaillement de 15 166 L le 15/07/2026 par NEPTUNE OIL (Cuve de 25 000 L livrée)",
    autonomieHeures: 420,
    visite: true
  },
  {
    id: 2,
    site: "BEPANDA NATIONAL 1",
    marque: "SDMO",
    puissance: "5000",
    etat: "F",
    cuvePrincipale: 5000,
    quantiteCuveP: 4520,
    cuveJournaliere: 1000,
    quantiteCuveJ: 1000,
    compteurHoraire: 1014,
    observation: "Ravitaillement de 3 087 Litres le 15/07/2026",
    autonomieHeures: 190,
    visite: true
  },
  {
    id: 3,
    site: "BEPANDA PETIT MARCHE",
    marque: "SDMO",
    puissance: "XXXX",
    etat: "F",
    cuvePrincipale: 1000,
    quantiteCuveP: 1000,
    cuveJournaliere: 0,
    quantiteCuveJ: 0,
    compteurHoraire: 1954,
    observation: "Données reconduites pour défaut véhicule",
    autonomieHeures: 80,
    visite: false
  },
  {
    id: 4,
    site: "BONALOKA",
    marque: "LIONROCK",
    puissance: "XXXX",
    etat: "HS",
    cuvePrincipale: 900,
    quantiteCuveP: 900,
    cuveJournaliere: 0,
    quantiteCuveJ: 0,
    compteurHoraire: 663,
    observation: "PAS D'INVERSEUR de Sources, GES A L'ARRET",
    autonomieHeures: 0,
    visite: false
  },
  {
    id: 5,
    site: "CT AKWA CENTRE",
    marque: "AKSA 4",
    puissance: "93",
    etat: "F",
    cuvePrincipale: 5000,
    quantiteCuveP: 4032,
    cuveJournaliere: 588,
    quantiteCuveJ: 588,
    compteurHoraire: 1283,
    observation: "Jauge dégradée / Lecture approximative à remplacer. Ravitaillement de 2 232 L le 15/07",
    autonomieHeures: 140,
    visite: true
  },
  {
    id: 6,
    site: "CT AKWA NORD",
    marque: "SDMO",
    puissance: "XXXX",
    etat: "F",
    cuvePrincipale: 3000,
    quantiteCuveP: 2100,
    cuveJournaliere: 300,
    quantiteCuveJ: 300,
    compteurHoraire: 892,
    observation: "Données reconduites pour défaut véhicule",
    autonomieHeures: 95,
    visite: false
  },
  {
    id: 7,
    site: "CT AKWA SUD",
    marque: "AKSA",
    puissance: "110",
    etat: "F",
    cuvePrincipale: 4000,
    quantiteCuveP: 3200,
    cuveJournaliere: 400,
    quantiteCuveJ: 400,
    compteurHoraire: 1420,
    observation: "Régulier / RAS",
    autonomieHeures: 110,
    visite: true
  },
  {
    id: 8,
    site: "DATA CENTER",
    marque: "PERKINS",
    puissance: "500",
    etat: "F",
    cuvePrincipale: 12000,
    quantiteCuveP: 11500,
    cuveJournaliere: 1000,
    quantiteCuveJ: 1000,
    compteurHoraire: 3410,
    observation: "Site hautement critique. Ravitaillement de 3 000 Litres effectué",
    autonomieHeures: 300,
    visite: true
  },
  {
    id: 9,
    site: "MBOPI",
    marque: "SDMO",
    puissance: "250",
    etat: "F",
    cuvePrincipale: 2500,
    quantiteCuveP: 1800,
    cuveJournaliere: 250,
    quantiteCuveJ: 250,
    compteurHoraire: null,
    observation: "Aucun barèmage disponible / Jauge à étalonner",
    autonomieHeures: 75,
    visite: true
  },
  {
    id: 10,
    site: "NDOGPASSI 1",
    marque: "OLYMPIAN",
    puissance: "150",
    etat: "F",
    cuvePrincipale: 1500,
    quantiteCuveP: 1100,
    cuveJournaliere: 150,
    quantiteCuveJ: 150,
    compteurHoraire: 750,
    observation: "Données reconduites",
    autonomieHeures: 60,
    visite: false
  },
  {
    id: 11,
    site: "NDOGPASSI 2",
    marque: "SDMO",
    puissance: "XXXX",
    etat: "P",
    cuvePrincipale: 710,
    quantiteCuveP: 710,
    cuveJournaliere: 0,
    quantiteCuveJ: 0,
    compteurHoraire: null,
    observation: "Compteur horaire Illisible sur le contrôleur du GES",
    autonomieHeures: 0,
    visite: false
  },
  {
    id: 12,
    site: "BONABERI 1",
    marque: "SDMO",
    puissance: "200",
    etat: "F",
    cuvePrincipale: 2000,
    quantiteCuveP: 1450,
    cuveJournaliere: 200,
    quantiteCuveJ: 200,
    compteurHoraire: 1105,
    observation: "Niveau cuve vérifié",
    autonomieHeures: 85,
    visite: true
  },
  {
    id: 13,
    site: "BONABERI 2",
    marque: "CATERPILLAR",
    puissance: "350",
    etat: "F",
    cuvePrincipale: 3000,
    quantiteCuveP: 2200,
    cuveJournaliere: 300,
    quantiteCuveJ: 300,
    compteurHoraire: 2150,
    observation: "RAS / Fonctionnement normal",
    autonomieHeures: 90,
    visite: true
  },
  {
    id: 14,
    site: "KOUMASSI",
    marque: "SDMO",
    puissance: "100",
    etat: "F",
    cuvePrincipale: 1000,
    quantiteCuveP: 800,
    cuveJournaliere: 100,
    quantiteCuveJ: 100,
    compteurHoraire: 540,
    observation: "Données reconduites pour défaut véhicule",
    autonomieHeures: 50,
    visite: false
  },
  {
    id: 15,
    site: "NEW BELL MAGASIN",
    marque: "SDMO (EX NDOKOTTI)",
    puissance: "150",
    etat: "F",
    cuvePrincipale: 1500,
    quantiteCuveP: 1200,
    cuveJournaliere: 150,
    quantiteCuveJ: 150,
    compteurHoraire: 980,
    observation: "Groupe déplacé depuis Ndokotti Poste",
    autonomieHeures: 65,
    visite: true
  },
  {
    id: 16,
    site: "VILLAGE",
    marque: "FG WILSON",
    puissance: "80",
    etat: "P",
    cuvePrincipale: 800,
    quantiteCuveP: 600,
    cuveJournaliere: 0,
    quantiteCuveJ: 0,
    compteurHoraire: 410,
    observation: "Problème d'alternateur / En attente pièce",
    autonomieHeures: 0,
    visite: true
  }
];